version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0
      - image: circleci/postgres:9.6.5-alpine-ram
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: fishingAdventure
    working_directory: ~/FishingAdventureService/FishingAdventure
    steps:
      - checkout:
          path: ~/FishingAdventureService
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: sudo apt-get update
      - run: sudo apt-get upgrade
      - run: sudo apt-get install postgresql-client
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test
  prepare-for-deploy:
    docker:
        - image: cimg/openjdk:11.0
    working_directory: ~/FishingAdventureService
    steps:
      - checkout:
          path: ~/FishingAdventureService
          
orbs:
  heroku: circleci/heroku@1.2.6
workflows:
  heroku_deploy:
    jobs:
      - build-and-test:
          filters:  # using regex filters requires the entire branch to match
                branches:
                  only:  # only branches matching the below regex filters will run
                    - feat(4.7)/deploy-workflow
      - prepare-for-deploy:
          filters:  # using regex filters requires the entire branch to match
                branches:
                  only:  # only branches matching the below regex filters will run
                    - feat(4.7)/deploy-workflow
      - heroku/deploy-via-git:
          filters:  # using regex filters requires the entire branch to match
                branches:
                  only:  # only branches matching the below regex filters will run
                    - feat(4.7)/deploy-workflow
          requires:
            - build-and-test
            - prepare-for-deploy
